blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/wowsel/ks-universal-chart/tree/main/docs
    about: Check our documentation before creating an issue
  - name: 💬 Questions & Discussions
    url: https://github.com/wowsel/ks-universal-chart/discussions
    about: Please ask and answer questions here