{{- range $name, $config := .Values.configs }}
apiVersion: v1
kind: {{ if eq $config.type "secret" }}Secret{{ else }}ConfigMap{{ end }}
metadata:
  name: {{ include "ks-universal.configName" (dict "root" $ "name" $name) }}
  labels:
    {{- include "ks-universal.labels" (dict "Chart" $.Chart "Release" $.Release "name" $name) | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
{{- if eq $config.type "secret" }}
type: Opaque
data:
  {{- range $key, $value := $config.data }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- else }}
data:
  {{- range $key, $value := $config.data }}
  {{- if contains "\n" ($value | toString) }}
  {{ $key }}: |
{{- $value | nindent 4 }}
  {{- else }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
  {{- end }}
{{- end }}
---
{{- end }}
