{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- if $deploymentConfig.pdb }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" (dict "Chart" $.Chart "Release" $.Release "name" $deploymentName) | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "ks-universal.deploymentSelector" (dict "name" $deploymentName "instance" $.Release.Name) | nindent 6 }}
  {{- if $deploymentConfig.pdb.minAvailable }}
  minAvailable: {{ $deploymentConfig.pdb.minAvailable }}
  {{- end }}
  {{- if $deploymentConfig.pdb.maxUnavailable }}
  maxUnavailable: {{ $deploymentConfig.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
---
{{- end }}
