{{/* Service helper template */}}
{{- define "ks-universal.service" -}}
{{- $serviceName := .serviceName }}
{{- $serviceConfig := .serviceConfig }}
{{- $root := .root }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $serviceName }}
  labels:
    {{- include "ks-universal.labels" (dict "Chart" $root.Chart "Release" $root.Release "name" $serviceName) | nindent 4 }}
spec:
  type: {{ $serviceConfig.type | default "ClusterIP" }}
  ports:
    {{- range $serviceConfig.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
      {{- if .nodePort }}
      nodePort: {{ .nodePort }}
      {{- end }}
      protocol: {{ .protocol | default "TCP" }}
    {{- end }}
  selector:
    {{- include "ks-universal.componentLabels" (dict "name" $serviceName "root" $root) | nindent 4 }}
{{- end }}
{{- include "ks-universal.validate" . -}}
{{/* Main service template */}}
{{- if .Values.services }}
{{- range $serviceName, $serviceConfig := .Values.services }}
---
{{- include "ks-universal.service" (dict "serviceName" $serviceName "serviceConfig" $serviceConfig "root" $) }}
{{- end }}
{{- end }}

{{/* Auto-created services from deployments */}}
{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- if $deploymentConfig.autoCreateService }}
{{- $ports := list }}
{{- range $containerName, $container := $deploymentConfig.containers }}
{{- range $portName, $port := $container.ports }}
{{- $ports = append $ports (dict "name" $portName "port" $port.containerPort "targetPort" $port.containerPort "protocol" (default "TCP" $port.protocol)) }}
{{- end }}
{{- end }}
{{- if $ports }}
---
{{- $serviceConfig := dict "ports" $ports "type" ($deploymentConfig.serviceType | default "ClusterIP") }}
{{- include "ks-universal.service" (dict "serviceName" $deploymentName "serviceConfig" $serviceConfig "root" $) }}
{{- end }}
{{- end }}
{{- end }}
