{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- $defaultedConfig := include "ks-universal.deploymentDefaults" (dict "deployment" $deploymentConfig "general" $.Values.deploymentsGeneral) | fromYaml }}
{{- if and $deploymentConfig.autoCreateServiceMonitor (include "ks-universal.hasMetricsPort" (dict "containers" $defaultedConfig.containers)) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $deploymentName }}
    {{- if $deploymentConfig.serviceMonitor }}
    {{- with $deploymentConfig.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "ks-universal.deploymentSelector" (dict "name" $deploymentName "instance" $.Release.Name) | nindent 6 }}
  endpoints:
  - port: http-metrics
{{- end }}
---
{{- end }}