{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- if and $deploymentConfig.serviceAccount (not $deploymentConfig.autoCreateServiceAccount) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" (dict "Chart" $.Chart "Release" $.Release "name" $deploymentName) | nindent 4 }}
    {{- $extraLabels := include "ks-universal.mergeLabels" (dict "root" $ "resourceLabels" $deploymentConfig.serviceAccount.labels) }}
    {{- if $extraLabels }}
    {{- $extraLabels | nindent 4 }}
    {{- end }}
  {{- $mergedAnnotations := include "ks-universal.mergeAnnotations" (dict "root" $ "resourceAnnotations" $deploymentConfig.serviceAccount.annotations) }}
  {{- if $mergedAnnotations }}
  annotations:
    {{- $mergedAnnotations | nindent 4 }}
  {{- end }}
{{- if and $.Values.generic $.Values.generic.extraImagePullSecrets }}
imagePullSecrets:
  {{- toYaml $.Values.generic.extraImagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
---
{{- end }}
