# serviceaccount.yaml
{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- if $deploymentConfig.serviceAccount }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $deploymentName }}
  {{- with $deploymentConfig.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- if and $.Values.generic $.Values.generic.extraImagePullSecrets (not (empty $.Values.generic.extraImagePullSecrets)) }}
imagePullSecrets:
  {{- toYaml $.Values.generic.extraImagePullSecrets | nindent 2 }}
{{- end }}
{{- end }}
{{- end }}