# auto-services.yaml
{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- if $deploymentConfig.autoCreateService }}
{{- $ports := list }}
{{- range $containerName, $container := $deploymentConfig.containers }}
{{- range $portName, $port := $container.ports }}
{{- $ports = append $ports (dict "name" $portName "port" $port.containerPort "targetPort" $port.containerPort "protocol" (default "TCP" $port.protocol)) }}
{{- end }}
{{- end }}
{{- if $ports }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $deploymentName }}
spec:
  type: {{ $deploymentConfig.serviceType | default "ClusterIP" }}
  ports:
    {{- toYaml $ports | nindent 4 }}
  selector:
    {{- include "ks-universal.deploymentSelector" (dict "name" $deploymentName "instance" $.Release.Name) | nindent 4 }}
{{- end }}
{{- end }}
{{- end }}