{{- if .Values.deployments }}
{{- range $deploymentName, $deploymentConfig := .Values.deployments }}
{{- $defaultedConfig := include "ks-universal.deploymentDefaults" (dict "deployment" $deploymentConfig "general" $.Values.deploymentsGeneral) | fromYaml }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $deploymentName }}
  labels:
    {{- include "ks-universal.labels" $ | nindent 4 }}
    app.kubernetes.io/component: {{ $deploymentName }}
  {{- if $defaultedConfig.annotations }}
  annotations:
    {{- toYaml $defaultedConfig.annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if and (not $deploymentConfig.hpa) $defaultedConfig.replicas }}
  replicas: {{ $defaultedConfig.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "ks-universal.deploymentSelector" (dict "name" $deploymentName "instance" $.Release.Name) | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "ks-universal.deploymentSelector" (dict "name" $deploymentName "instance" $.Release.Name) | nindent 8 }}
      {{- if $defaultedConfig.podAnnotations }}
      annotations:
        {{- toYaml $defaultedConfig.podAnnotations | nindent 8 }}
      {{- end }}
    spec:
      {{- if $deploymentConfig.serviceAccount }}
      serviceAccountName: {{ $deploymentName }}
      {{- end }}
      {{- if and $.Values.generic (hasKey $.Values.generic "extraImagePullSecrets") }}
      imagePullSecrets:
        {{- toYaml $.Values.generic.extraImagePullSecrets | nindent 8 }}
      {{- end }}
      {{- if $defaultedConfig.securityContext }}
      securityContext:
        {{- toYaml $defaultedConfig.securityContext | nindent 8 }}
      {{- end }}
      containers:
      {{- include "ks-universal.containers" (dict "root" $ "containers" $defaultedConfig.containers) | nindent 8 }}
      {{- $affinity := include "ks-universal.processAffinity" (dict "config" $defaultedConfig "deploymentName" $deploymentName "general" $.Values.deploymentsGeneral) | fromYaml }}
      {{- if $affinity }}
      affinity:
        {{- toYaml $affinity | nindent 8 }}
      {{- end }}
      {{- if $defaultedConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml $defaultedConfig.nodeSelector | nindent 8 }}
      {{- end }}
      {{- if $defaultedConfig.tolerations }}
      tolerations:
        {{- toYaml $defaultedConfig.tolerations | nindent 8 }}
      {{- end }}
{{- end }}
{{- end }}